services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5

  #hasura:
  #  image: hasura/graphql-engine:latest
  #  depends_on:
  #    - postgres
  #  ports:
  #    - "8080:8080"
  #  restart: always
  #  environment:
  #    HASURA_GRAPHQL_DATABASE_URL: postgres://itmahesh:Mahesh_23@postgres:5432/mydatabase
  #    HASURA_GRAPHQL_ADMIN_SECRET: Mahesh_23
  #    HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
  #    HASURA_GRAPHQL_JWT_SECRET: '{ "type": "HS256", "key": "oursupersecretsupersecurekey1234567890" }'
  react-prod:
    build:
      context: ./frontend/react
      dockerfile: Dockerfile.prod
    ports:
      - "3000:80"
    restart: always
  react-dev:
    build:
      context: ./frontend/react
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/react:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
  python:
    build:
      context: ./backend/python
      dockerfile: Dockerfile
    container_name: flask
    depends_on:
      - redis
      - postgres
    ports:
      - "5000:5000"
    volumes:
      - ./backend/python:/app
    environment:
      - FLASK_ENV=development
    command: python app.py

  worker:  
    build:
      context: ./backend/worker
      dockerfile: Dockerfile
    container_name: python_worker  
    depends_on:
      - postgres
      - python
      - redis 
    volumes:
      - ./backend/worker:/app 
    environment:
      - FLASK_ENV=development
      - REDIS_HOST=redis 
      - REDIS_PORT=6379
      - API_URL=http://python:5000/api/notificacoes 
    command: python worker.py

  redis:
    image: redis:alpine
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes # persistência para não perder dados se container reiniciar
  redis-commander: # Web-UI
    image: rediscommander/redis-commander:latest
    container_name: redis-ui
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
      
volumes:
  postgres_data:

